### ISSUE TITLE
Outlook conf file issue

### ISSUE THREAD

**Issue by kimthostrup** [jango/todoist-email-tasks#1]
Hi,

After typing in the api-key and installing the requirrements, and I try to run the todoist.outlook.py I get the following error, which I supect is related to outlook 2010

[Anaconda2] c:\todoist>python todoist.outlook.py
Traceback (most recent call last):
  File "todoist.outlook.py", line 125, in <module>
    main()
  File "todoist.outlook.py", line 50, in main
    config = runpy.run_path(os.path.join(MY_LOCATION, "todoist.conf"))
  File "C:\Users\kimt\AppData\Local\Continuum\Anaconda2\lib\runpy.py", line 239, in run_path
    code = _get_code_from_file(path_name)
  File "C:\Users\kimt\AppData\Local\Continuum\Anaconda2\lib\runpy.py", line 220, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "c:\todoist\todoist.conf", line 4
    Todoist Project ID (int)
                  ^
SyntaxError: invalid syntax

[Anaconda2] c:\todoist>

----snip----
TODOIST_API_TOKEN = '698d208cd7e186ceef2365xxxxxxxxxxx' 
# Todoist Token (str)
TODOIST_PROJECT_ID_GMAIL = 0 
Todoist Project ID (int)
TODOIST_PROJECT_ID_OUTLOOK = 2F170560653
Outlook Project ID (int) 
----snip----

Thanks in advance.
Kim

**Comment by jango** [comment]
Hi Kim,

`code = compile(f.read(), fname, 'exec')`

This line attempts to read the configuration file that must look like a *valid* Python file, so if you either remove the lines that don't start with # (i.e. Todoist Token (str), Todoist Project ID (int), Outlook Project ID (int)) or if you add a # in front of those lines, this exception should no longer occur.

Let me know if it works,
Nikita
